name: CI Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        clingconversion: [5.1.0]

    
    steps:
    - uses: actions/checkout@v2

    - name: Install clingcon
      run: |
        sudo add-apt-repository ppa:potassco/wip
        sudo apt-get update
        sudo apt-get install clingcon=${{ matrix.clingconversion }}-focal5
    - name: Test clingcon
      run: clingcon --version

    - name: Install minizinc
      run: | 
        wget https://github.com/MiniZinc/MiniZincIDE/releases/download/2.6.0/MiniZincIDE-2.6.0-bundle-linux-x86_64.tgz
        tar xzf MiniZincIDE-2.6.0-bundle-linux-x86_64.tgz
        echo "$(pwd)/MiniZincIDE-2.6.0-bundle-linux-x86_64/bin" >> $GITHUB_PATH
    - name: Test minizinc
      run: minizinc --version

    - name: Install fzn2lp
      run: |
        wget https://github.com/potassco/fzn2lp/releases/download/v0.1.3/fzn2lp-linux-x86_64.tar.gz
        tar -xvf fzn2lp-linux-x86_64.tar.gz
        echo "$(pwd)" >> $GITHUB_PATH
    - name: Test fzn2lp
      run: fzn2lp --version

    - name: Install flatzingo
      run: ./install.sh

    - name: Install python stuff
      run: |
        sudo apt-get install -y python3-pip
        pip3 install pytest
        pip3 install --extra-index-url https://test.pypi.org/simple/ clingcon==${{ matrix.clingconversion }}.post4

    - name: Test flatzingo
      run: python3 -m pytest tests

    - name: Install minizinc testcases
      uses: actions/checkout@v2
      with:
        repository: 'MiniZinc/libminizinc'
        ref: '2.6.0'
        path: 'libminizinc'
    - name: Install minizinc python library and requirements
      run: pip3 install -r libminizinc/tests/requirements.txt
    - name: Prepare minizinc testcases
      run: sed -i 's/"gecode", "cbc", "chuffed"/"flatzingo"/' libminizinc/tests/minizinc_testing/spec.py
    - name: Run minizinc tests
      run: |
        cd libminizinc/tests
        pytest -k "not parse_assignments and not nonbool_constraint and not var_ann_ and not var_ann_comprehension and not var_set_bool and not var_set_float and not var_string_ and not var_string_comprehension and not output_only_fn and not float_mod_crash and not float_div_crash and not non-set-array-ti-location and not output_only_no_rhs and not quoted_id_ozn and not dzn_output_array and not test_array1d_bad_ and not assert_bad_ and not test_var_set_element and not bug269 and not bug347 and not test-search1" --driver=../../MiniZincIDE-2.6.0-bundle-linux-x86_64/bin

