name: CI Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    
    steps:
    - uses: actions/checkout@v2

    - name: Install clingcon
      run: |
        sudo add-apt-repository ppa:potassco/stable
        sudo apt-get update
        sudo apt-get install clingcon=5.0.0-focal1
    - name: Test clingcon
      run: clingcon --version

    - name: Install minizinc
      run: | 
        wget https://github.com/MiniZinc/MiniZincIDE/releases/download/2.5.5/MiniZincIDE-2.5.5-bundle-linux-x86_64.tgz
        tar xzf MiniZincIDE-2.5.5-bundle-linux-x86_64.tgz
        echo "$(pwd)/MiniZincIDE-2.5.5-bundle-linux-x86_64/bin" >> $GITHUB_PATH
#    - name: Install Minizinc
#      uses: engineerd/configurator@v0.0.6
#      with:
#        name: minizinc
#        url: https://github.com/MiniZinc/MiniZincIDE/releases/download/2.5.5/MiniZincIDE-2.5.5-bundle-linux-x86_64.tgz
#        pathInArchive: MiniZincIDE-2.5.5-bundle-linux-x86_64/bin/minizinc
    - name: Test minizinc
      run: minizinc --version

    - name: Install fzn2lp
      uses: engineerd/configurator@v0.0.6
      with:
        name: fzn2lp
        fromGitHubReleases: "true"
        repo: "potassco/fzn2lp"
        version: "latest"
        urlTemplate: "https://github.com/potassco/fzn2lp/releases/download/{{version}}/fzn2lp-linux-x86_64.tar.gz"
        pathInArchive: fzn2lp
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Test fzn2lp
      run: fzn2lp --version

    - name: Install flatzingo
      run: ./install.sh

    - name: Install python stuff
      run: |
        sudo apt-get install -y python3-pip
        pip3 install pytest
        pip3 install clingcon==5.5.0

    - name: Test flatzingo
      run: python3 -m pytest tests
