name: CI Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        clingconversion: [5.0.0]

    
    steps:
    - uses: actions/checkout@v2

    - name: Install clingcon
      run: |
        sudo add-apt-repository ppa:potassco/stable
        sudo apt-get update
        sudo apt-get install clingcon=${{ matrix.clingconversion }}-focal1
    - name: Test clingcon
      run: clingcon --version

    - name: Install minizinc
      run: | 
        wget https://github.com/MiniZinc/MiniZincIDE/releases/download/2.5.5/MiniZincIDE-2.5.5-bundle-linux-x86_64.tgz
        tar xzf MiniZincIDE-2.5.5-bundle-linux-x86_64.tgz
        echo "$(pwd)/MiniZincIDE-2.5.5-bundle-linux-x86_64/bin" >> $GITHUB_PATH
    - name: Test minizinc
      run: minizinc --version

    - name: Install fzn2lp
      run: |
        wget https://github.com/potassco/fzn2lp/releases/download/latest/fzn2lp-linux-x86_64.tar.gz
        tar -xvf fzn2lp-linux-x86_64.tar.gz
        echo "$(pwd)/fzn2lp-linux-x86_64" >> $GITHUB_PATH
    - name: Test fzn2lp
      run: fzn2lp --version

    - name: Install flatzingo
      run: ./install.sh

    - name: Install python stuff
      run: |
        sudo apt-get install -y python3-pip
        pip3 install pytest
        pip3 install clingcon==${{ matrix.clingconversion }}

    - name: Test flatzingo
      run: python3 -m pytest tests
